import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { validateTokens, emit, writeEmitted, HEADER_MARK } from '../scripts/emit-tokens.mjs';

const sample = {
  duration: { hover: 150, bumpPeak: 350 },
  easing: { enter: [0, 0, 0.58, 1] },
  distance: { enter: 10 },
  scale: { bump: 1.4 },
  focus: { width: 2, offset: 0 },
};

test('valid tokens have no errors', () => {
  assert.deepEqual(validateTokens(sample), []);
});

test('rejects unknown groups, bad names, bad durations and bad easings', () => {
  const errors = validateTokens({ color: {}, duration: { 'Bad-Name': 1, slow: 0, frac: 1.5 }, easing: { wild: [1.2, 0, 0.5, 1] } });
  assert.equal(errors.length, 5);
  assert.match(errors.join('\n'), /unknown group "color"/);
  assert.match(errors.join('\n'), /easing\.wild/);
});

test('css uses neutral kebab-case names and units', () => {
  const css = emit(sample, 'css');
  assert.match(css, /--motion-duration-hover: 150ms;/);
  assert.match(css, /--motion-duration-bump-peak: 350ms;/);
  assert.match(css, /--motion-easing-enter: cubic-bezier\(0, 0, 0\.58, 1\);/);
  assert.match(css, /--motion-distance-enter: 10px;/);
  assert.match(css, /--motion-scale-bump: 1\.4;/);
  assert.match(css, /--focus-width: 2px;/);
});

test('scss, ts and rust carry the same values', () => {
  assert.match(emit(sample, 'scss'), /\$motion-duration-hover: 150ms;/);
  const ts = emit(sample, 'ts');
  assert.match(ts, /duration: \{ hover: 150, bumpPeak: 350 \}/);
  assert.match(ts, /easing: \{ enter: 'cubic-bezier\(0, 0, 0\.58, 1\)' \}/);
  assert.match(ts, /export const focus = \{ width: 2, offset: 0 \} as const;/);
  const rs = emit(sample, 'rust');
  assert.match(rs, /pub const BUMP_PEAK: std::time::Duration = std::time::Duration::from_millis\(350\);/);
  assert.match(rs, /pub const ENTER: \[f32; 4\] = \[0\.0, 0\.0, 0\.58, 1\.0\];/);
  assert.match(rs, /pub const ENTER_PX: f32 = 10\.0;/);
});

test('emitted files never mention the skill or AI', () => {
  for (const target of ['css', 'scss', 'ts', 'rust']) {
    assert.doesNotMatch(emit(sample, target), /considered|claude|\bai\b|generated by/i);
  }
});

test('refuses to overwrite a hand-written file unless forced', () => {
  const dir = mkdtempSync(join(tmpdir(), 'cx tokens '));
  const out = join(dir, 'motion.css');
  writeFileSync(out, ':root { --mine: 1px; }\n');
  assert.throws(() => writeEmitted(out, emit(sample, 'css')), /refusing to overwrite/);
  writeEmitted(out, emit(sample, 'css'), { force: true });
  assert.match(readFileSync(out, 'utf8'), new RegExp(HEADER_MARK));
  writeEmitted(out, emit(sample, 'css')); // regenerating a generated file is allowed
});

test('unknown target throws', () => {
  assert.throws(() => emit(sample, 'swift'), /Unknown target/);
});
